Add: German language Error Message
skwasjer/IbanNet pull request #28
Opened 2021-04-14 14:22 UTC by AndreasSummer

thanks for the great library.
We have submitted a German translation of the rule messages

2021-04-17 16:13 UTC, skwasjer requested changes
Thanks for your contrib, I have reviewed it. Could you also target the `develop` branch instead?

2021-04-17 16:13 UTC, skwasjer commented on src/IbanNet/Resources.resx
> +    Version 2.0
Please revert this file. I will check after merge if we can even use newer schema, I remember having issues with the newer code generators with building the .NET Standard 1 targets in some odd cases, f.ex. after adding a new string resource.

2021-04-17 16:13 UTC, skwasjer commented on test/IbanNet.Tests/Localisation/GermanLanguageTest.cs
> +                System.Threading.Thread.CurrentThread.CurrentUICulture = before;
Restoring the wrong property (`CurrentCulture`):

[L20](https://github.com/skwasjer/IbanNet/pull/28/files#diff-87475bc9cf484ce05297f72718c71e183c0a1323f8e150a414df1428bdc8ae60R20):
```
System.Globalization.CultureInfo before = System.Threading.Thread.CurrentThread.CurrentCulture;
```

2021-04-17 16:13 UTC, skwasjer commented on test/IbanNet.Tests/Localisation/GermanLanguageTest.cs
> +                System.Threading.Thread.CurrentThread.CurrentUICulture = before;
Restoring the wrong property (`CurrentCulture`):

[L51](https://github.com/skwasjer/IbanNet/pull/28/files#diff-87475bc9cf484ce05297f72718c71e183c0a1323f8e150a414df1428bdc8ae60R51):
```
System.Globalization.CultureInfo before = System.Threading.Thread.CurrentThread.CurrentCulture;
```

2021-04-17 16:13 UTC, skwasjer commented on test/IbanNet.Tests/Localisation/GermanLanguageTest.cs
> +        public void GermanLanguageTestInvalidLenght()
Please follow the given-when-then convention used through the library, including use of FluentAssertions instead of Assert.

2021-04-20 06:44 UTC, AndreasSummer commented
will be done. 👍

2021-04-20 06:55 UTC, AndreasSummer commented
Sorry for the wrong commitment #29. overlooked the other comments

2021-08-21 02:23 UTC, skwasjer commented
There are two MR's addressing the same feature, the review comments have not been addressed, and new changes to IbanNet have caused this PR to divert (merge conflicts). As such, closing, feel free to reopen once you have an update.

2021-08-21 02:23 UTC, closed without merging